Repository mercadopago/px-ios, pull requests merged in 2019-07, with the labels that each got.

#1938 Credits first implementation
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapCreditsDto.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDto.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethodSearch+Business.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentTypes.swift
  MercadoPagoSDK/MercadoPagoSDK/Plist/PaymentMethodSearch.plist
  MercadoPagoSDK/MercadoPagoSDK/RevampImages.xcassets/Payment Methods ON/Credits/Contents.json
  MercadoPagoSDK/MercadoPagoSDK/RevampImages.xcassets/Payment Methods ON/Credits/consumerCredits.imageset/2019-06-21 (1).png
  MercadoPagoSDK/MercadoPagoSDK/RevampImages.xcassets/Payment Methods ON/Credits/consumerCredits.imageset/Contents.json
  MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
Labels: CREDITS, DO NOT MERGE

#1939 DTOs improved
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXCreditsDisplayInfo.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXLinkableAction.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXLinkablePhraseDto.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapCreditsDto.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXResultInfo.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXTermsDto.swift
Labels: CREDITS

#1944 Payer costs step
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethod+Business.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentTypes.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PaymentType.swift
Labels: CREDITS

#1946 change payment method box fixed
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
Labels: CREDITS

#1948 Extended pay button container for credits case
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXCreditsDisplayInfo.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXLinkableAction.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXResultInfo.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentMethod.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonComponent.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonRenderer.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterProps.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
Labels: CREDITS

#1949 add terms view to extended container
  MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonRenderer.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift
Labels: CREDITS

#1950 terms information and delegate
  MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonComponent.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonRenderer.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift
Labels: CREDITS

#1947 Se agrega productId como header al endpoint de pagos
  MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift
Labels: PagoPreferencias

#1945 Nuevo endpoint de pagos
  MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore+Encodable.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/MPPayment.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData+Encodable.swift
Labels: DO NOT MERGE, PagoPreferencias

#1964 Diseño de tarjeta de mercadoCreditos en oneTap
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift
Labels: DO NOT MERGE

#1968 Se agrega overlayMask a la tarjeta de mercadoCredits
  MercadoPagoSDK/MercadoPagoSDK/RevampImages.xcassets/Payment Methods ON/Credits/creditsOverlayMask.imageset/Contents.json
  MercadoPagoSDK/MercadoPagoSDK/RevampImages.xcassets/Payment Methods ON/Credits/creditsOverlayMask.imageset/creditsOverlayMask.pdf
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift
Labels: CREDITS

#1936 [Feature] Pay preference
  MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore+Encodable.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlowModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckoutViewModel+InitFlow.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/MPPayment.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXBackUrls.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData+Encodable.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayer.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderViewModelHelper.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
Labels: DO NOT MERGE, PagoPreferencias

#1976 Credits prod url
  MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift
Labels: DO NOT MERGE

#1971 Refactor - Using golden rate for one tap cards
  CHANGELOG.md
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m
  MercadoPagoSDK/MercadoPagoSDK/Core/Utils.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/AccountMoneyCard.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.xib
  MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderSizeManager.swift
  MercadoPagoSDKV4.podspec
Labels: DO NOT MERGE
