Repository mercadopago/px-ios, pull requests merged in 2020-01, with the labels that each got.

#2115 Mejoras sobre ESC
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomComponentText.swift
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/InstallmentsTableViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MLMyMPPXTrackListener.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MPTheme.swift
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MediosOffTableViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MediosOffTableViewController.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MeliTheme.swift
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC-Bridging-Header.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentMethodPluginConfigViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentMethodPluginConfigViewController.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PrefixHeader.pch
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/SavedCardsTableViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultFormViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultViewController.h
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultViewController.m
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/ESC/MercadoPagoESC.swift
  MercadoPagoSDK/MercadoPagoSDK/Core/ESC/PXESCManager.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlowModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCustomOptionSearchItem.swift
  MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
  MercadoPagoSDKV4.podspec
Labels: Status: Review Needed, esc

#2114 Congrats con descuentos
  ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
  MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
Labels: Status: Review Needed, Type: Enhancement

#2118 FIX - Business result help message
  MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultBodyComponent.swift
  MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift
Labels: Status: Review Needed, Type: Bug
